### ISSUE TITLE
ionic build/emulate or npm build fails

### ISSUE THREAD

**Issue by CelsoSantos** [driftyco/ionic-app-scripts#104]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
ionic build or ionic emulate are failing with ngc error:
```
[11:09:30]  ngc: Error: Error at /Users/dev/Syone/brandbassador/ionic-rc0/.tmp/pages/settings/settings.ngfactory.ts:205:45: Property 'desktop' does not exist on type 'Settings'.
```

#### What behavior are you expecting?
Being able to run a simple sample app on ionic emulator

**Steps to reproduce:**
1. Make an application based running ionic app --v2 MyApp
2. Copy sample page/component into pages
3. Adapt code according to requirements of Angular2
4. Run `ionic emulate ios` or `ionic build ios`

```
[11:09:15]  lint finished in 1.37 s
[11:09:30]  ngc: Error: Error at /Users/dev/Syone/brandbassador/ionic-rc0/.tmp/pages/settings/settings.ngfactory.ts:205:45: Property 'desktop' does not exist on type 'Settings'.
    at check (/Users/dev/Syone/brandbassador/ionic-rc0/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/Users/dev/Syone/brandbassador/ionic-rc0/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /Users/dev/Syone/brandbassador/ionic-rc0/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3


[11:09:30]  ngc: Compilation failed


[11:09:30]  ngc failed:  NGC encountered an error

[11:09:30]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (/Users/dev/Syone/brandbassador/ionic-rc0/node_modules/@ionic/app-scripts/dist/ngc.js:62:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error running ionic app script "build": Error: NGC encountered an error
```

**Which @ionic/app-scripts version are you using?**
0.0.29

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dev/.nvm/versions/node/v6.7.0/bin/node',
1 verbose cli   '/Users/dev/.nvm/versions/node/v6.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ionic-hello-world@~prebuild: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prebuild: no script for prebuild, continuing
7 info lifecycle ionic-hello-world@~build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~build: PATH: /Users/dev/.nvm/versions/node/v6.7.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/dev/Syone/brandbassador/ionic-rc0/node_modules/.bin:/Users/dev/.nvm/versions/node/v6.7.0/bin:/Users/dev/.nvm/versions/node/v6.7.0/bin:/Users/dev/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
10 verbose lifecycle ionic-hello-world@~build: CWD: /Users/dev/Syone/brandbassador/ionic-rc0
11 silly lifecycle ionic-hello-world@~build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle ionic-hello-world@~build: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~build: Failed to exec build script
14 verbose stack Error: ionic-hello-world@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/dev/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/dev/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /Users/dev/Syone/brandbassador/ionic-rc0
17 error Darwin 15.6.0
18 error argv "/Users/dev/.nvm/versions/node/v6.7.0/bin/node" "/Users/dev/.nvm/versions/node/v6.7.0/bin/npm" "run" "build"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ionic-hello-world@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is actually NGC throwing about a legit error in your code. NGC does type checking of variables and methods bound in your template, which means it can also throw type errors. Just from glancing at the error it seems as if you have an interface or object called `Settings` that you are trying to use a property called `desktop` from but that property does not actually exist on that object. Because this is not an Ionic error but actually an error in your code I am going to close this issue for now. Thanks!

**Comment by rubimazaki** [comment]
Hi, got the same issue but with RC1. Where did you see that this is the NGC?

**Comment by n1t1nv3rma** [comment]
Correct, I had same issue and fixed with moving all return type from "static get parameters() {..." into the constructor()
