### ISSUE TITLE
ngc error with ng2-translate

### ISSUE THREAD

**Issue by rajhub** [driftyco/ionic-app-scripts#113]
I'm using ng2-translate for localization and the import section on app.module.ts is causing this problem:
```
  imports: [
    CommonModule,
    BrowserModule,
    HttpModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(Config.fbConfig),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      // this line below is causing trouble
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),       deps: [Http]
    })
  ]
```

I get this error:
```
[21:34:42]  ngc error: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 83:19 in the original .ts file), resolving symbol AppModule in /Users/raj/Bitbucket/vk/vk-app/.tmp/app/app.module.ts
    at simplifyInContext (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/static_reflector.js:469:23)
    at StaticReflector.simplify (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/static_reflector.js:472:22)
    at StaticReflector.annotations (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/codegen.js:53:54)
    at CodeGenerator.readFileMetadata (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/codegen.js:66:13)
    at /Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/codegen.js:100:35)
    at codegen (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/raj/Bitbucket/vk/vk-app/node_modules/@angular/tsc-wrapped/src/main.js:30:16)


[21:34:42]  ngc error: Compilation failed
```
I'm using the latest app-scripts

**Comment by Kobzol** [comment]
The error is telling you what you have to do, you have to move the useFactory method to an exported function.

so change useFactory (http: ...
to useFactory: someFunction

and create 
export someFunction(http: ..)
{ return nrw TranslateStatic... }
Do not call someFunction, just assign it to useFactory. Also upgrade to the latest ng2-translate if you haven't already, it received fixes to be AOT compatible :-)

**Comment by rajhub** [comment]
@Kobzol thank you, that worked
