### ISSUE TITLE
Maximum call stack size exceeded still reached with version 0.0.30

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#121]
Hi,

I didn't found clearly in the issues of this project app-scripts if the following problem was already solved or still open. Therefore in case it won't be, here just a message to tell you that even with version 0.0.30 of the ionic-app-scripts, the "maximum call stack size exceeded" error msg could be still reached

     [13:28:19]  bundle dev update started ...
     [13:28:19]  bundle dev update failed:  Maximum call stack size exceeded
     [13:28:19]  RangeError: Maximum call stack size exceeded
         at isArray (native)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:157:7)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
         at deepClone (/Users/me/Documents/projects/myproject/node_modules/rollup/dist/rollup.js:165:18)
     
     JS changed:   www/build/main.js

BR

**Comment by jgw96** [comment]
Hello @peterpeterparker would you mind giving this a test again with the latest version of app-scripts? To update you can run `npm install @ionic/app-scripts@latest --save-dev`. Thanks!

**Comment by peterpeterparker** [comment]
@jgw96 I tried, made many html, ts and scss changes in a row and it seems to be fixed now, awesome!

Thx a lot
