### ISSUE TITLE
Build with ES2015 dependencies

### ISSUE THREAD

**Issue by urielhdz** [driftyco/ionic-app-scripts#132]
When using a dependency that uses some ES2015 functionalities, such as (<https://github.com/dfahlander/Dexie.js>), the building process does not work, due to a problem with uglify-js and some ES2015 features, like the arrow function.

I'd like to know if there is a way we could skip the uglify process for those cases, or using a uglifier that works with ES2015, per http://stackoverflow.com/questions/38429567/some-es6-features-are-not-understood-by-grunt-uglify-js uglify-js there's a branch of uglifyJS that works with ES6: https://github.com/mishoo/UglifyJS2/tree/harmony

**Steps to reproduce:**
1. Create a new project
2. Add a ES2015 library, like Dexie.js to the dependencies
3. Build the application

When trying to run the application with Android: `ionic run android -l -c`

```
at new JS_Parse_Error (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at unexpected (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)
    at expr_atom (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:13)
    at maybe_unary (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)
    at expr_ops (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)
    at maybe_conditional (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)
    at maybe_assign (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)
    at expression (eval at <anonymous> (/Users/urielhernandez/Documents/dev/ionic/photoMap/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2878:20)
```

I know this is not a problem related to the Ionic Scripts, but it brakes it, my suggestions are that we could avoid the uglify process, or change the uglifier.

Thank you 🙂

**Comment by urielhdz** [comment]
It's worth mention that I don't have the error on my application, I fixed it by importing a non es6 version of the library.

So, I was wondering if the recommendation here could be, don't libraries that are only written on ES6 ?

**Comment by danbucholtz** [comment]
@urielhdz,

It is not best practice to distribute code that needs to be transpiled.

Having said that ... I hope more teams start doing it 💯 because it enables us to minify it further in some cases.

I am thinking we may add pre and post hooks to the bundling process that developers can hook into this. This would enable developers to do anything they needed to do, such as text replacement, transpiling, etc.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Let's track this issue [here](https://github.com/driftyco/ionic-app-scripts/issues/55).

Thanks,
Dan
