### ISSUE TITLE
cannot build main.css and main.js 

### ISSUE THREAD

**Issue by Gtanxingwen** [driftyco/ionic-app-scripts#148]
[10:51:20]  lint finished in 4.21 s
[10:51:31]  Error reading template file, "build/pages/tabs/tabs.html": Error: ENOENT: no such file or directory, open 'D:\ArvixGtan\ionic\mynewapp\src\pages\tabs\build\pages\tabs\tabs.html'

[10:51:42]  Error reading template file, "search.component/search.component.html": Error: ENOENT: no such file or directory, open 'D:\ArvixGtan\ionic\mynewapp\src\pages\find\search.component\search.component\search.component.html'

[10:51:42]  bundle dev failed:  Could not resolve '../../../common/serve-url' from D:\ArvixGtan\ionic\mynewapp\src\pages\houses\housesdata.service.ts

[10:51:42]  Error: Could not resolve '../../../common/serve-url' from D:\ArvixGtan\ionic\mynewapp\src\pages\houses\housesdata.service.ts
    at Error (native)
    at D:\ArvixGtan\ionic\mynewapp\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
    at D:\ArvixGtan\ionic\mynewapp\node_modules\browser-resolve\index.js:265:24
    at D:\ArvixGtan\ionic\mynewapp\node_modules\resolve\lib\async.js:55:18
    at load (D:\ArvixGtan\ionic\mynewapp\node_modules\resolve\lib\async.js:69:43)
    at onex (D:\ArvixGtan\ionic\mynewapp\node_modules\resolve\lib\async.js:92:31)
    at D:\ArvixGtan\ionic\mynewapp\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)

ionic info 
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v6.2.0

help !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Gtanxingwen** [comment]
@jgw96  can you help me ....

**Comment by karvannan-thi** [comment]
404 error for main .css
sass cant build css file
<br>
ionic info
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.9.0
