### ISSUE TITLE
can't resolve module @angular/core/src/di/opaque_token

### ISSUE THREAD

**Issue by aherbots** [driftyco/ionic-app-scripts#348]
#### What behavior are you expecting?
Yesterday I had no issues but since I updated to the new ionic-app-scripts, I'm getting errors when running ionic build windows. 

**Steps to reproduce:**
1.` npm install @ionic/app-scripts@latest --save-dev`
2. added 
 ```
 "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch"
  }, 
```
to the package.json
3. `ionic build windows`

**Which @ionic/app-scripts version are you using?**

**Other information:** 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\aherbots\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:build' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'preionic:build', 'ionic:build', 'postionic:build' ]
5 info lifecycle aliaxiscontact@~preionic:build: aliaxiscontact@
6 silly lifecycle aliaxiscontact@~preionic:build: no script for preionic:build, continuing
7 info lifecycle aliaxiscontact@~ionic:build: aliaxiscontact@
8 verbose lifecycle aliaxiscontact@~ionic:build: unsafe-perm in lifecycle true
9 verbose lifecycle aliaxiscontact@~ionic:build: PATH: C:\Users\aherbots\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\aherbots\Workspace\aliaxiscontact\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\wapt;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\Git\bin\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\aherbots\AppData\Local\Microsoft\WindowsApps;C:\Users\aherbots\AppData\Local\atom\bin;C:\Users\aherbots\AppData\Roaming\npm
10 verbose lifecycle aliaxiscontact@~ionic:build: CWD: C:\Users\aherbots\Workspace\aliaxiscontact
11 silly lifecycle aliaxiscontact@~ionic:build: Args: [ '/d /s /c', 'ionic-app-scripts build' ]
12 silly lifecycle aliaxiscontact@~ionic:build: Returned: code: 1  signal: null
13 info lifecycle aliaxiscontact@~ionic:build: Failed to exec ionic:build script
14 verbose stack Error: aliaxiscontact@ ionic:build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\aherbots\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\aherbots\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aliaxiscontact@
16 verbose cwd C:\Users\aherbots\Workspace\aliaxiscontact
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aherbots\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error aliaxiscontact@ ionic:build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the aliaxiscontact@ ionic:build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aliaxiscontact package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs aliaxiscontact
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls aliaxiscontact
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by danbucholtz** [comment]
@aherbots,

Can you post the content on your package.json file as well as the entire output from running `ionic build windows`.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I cannot recreate this. Can you blow away your `node_modules`, do a fresh `npm install` and try again? I'll reopen the issue if needed.

Thanks,
Dan

**Comment by aherbots** [comment]
Sorry for the late responce! 

Already tried deleting and reinstalling the node_modules, didn't work.
After some digging I started thinking that it might have something to do with my file structure

[tree.txt](https://github.com/driftyco/ionic-app-scripts/files/588430/tree.txt)

**Comment by GRRedWings** [comment]
Any resolution to this?

**Comment by Andoion** [comment]
Nope, i've just put everything back to the old versions and now it runs again.
