### ISSUE TITLE
ionic rc2 failed in build

### ISSUE THREAD

**Issue by ishumt** [driftyco/ionic-app-scripts#350]
Hi 

my project is failing while build, it was fine untill RC0, but now i am getting errors, it is fine with IONIC SERVE, can some one help please?

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
C:\mobile_app_ionic\mtlDemo>ionic build android

Running 'build:before' npm script before build

> MTLDemo@ build C:\mobile_app_ionic\mtlDemo
> ionic-app-scripts build

[13:46:34]  ionic-app-scripts 0.0.39
[13:46:34]  build prod started ...
[13:46:34]  clean started ...
[13:46:34]  clean finished in 3 ms
[13:46:34]  copy started ...
[13:46:34]  ngc started ...
[13:46:34]  copy finished in 799 ms
[13:46:34]  lint started ...
[13:46:55]  lint finished in 20.28 s
[13:47:29]  Error: Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/login/login.ngfactory.ts:819:63
[13:47:29]  Property 'username' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/login/login.ngfactory.ts:839:63
[13:47:29]  Property 'email' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/login/login.ngfactory.ts:859:63
[13:47:29]  Property 'password' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/signup/signup.ngfactory.ts:986:63
[13:47:29]  Property 'p_person_id' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/signup/signup.ngfactory.ts:1001:63
[13:47:29]  Property 'p_surname' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/signup/signup.ngfactory.ts:1018:63
[13:47:29]  Property 'p_dob' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/signup/signup.ngfactory.ts:1033:63
[13:47:29]  Property 'p_email' does not exist on type '{ [key
[13:47:29]  string]: AbstractControl; }'.
[13:47:29]  Error at C:/mobile_app_ionic/mtlDemo/.tmp/pages/signup/signup.ngfactory.ts:1060:119
[13:47:29]  Property 'pw_mismatch' does not exist on type '{ [key
[13:47:29]  string]: any; }'.
[13:47:29]  ngc failed
[13:47:29]  ionic-app-script task: "build"
[13:47:29]  Error: Error

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--color"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! MTLDemo@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MTLDemo@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the MTLDemo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs MTLDemo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls MTLDemo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mobile_app_ionic\mtlDemo\npm-debug.log
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

C:\mobile_app_ionic\mtlDemo>events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1036:11)
    at Socket._writeGeneric (net.js:705:26)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Console.log (console.js:43:16)
    at C:\mobile_app_ionic\mtlDemo\node_modules\@ionic\app-scripts\dist\util\logger.js:169:21
    at Array.forEach (native)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch" "--color"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! MTLDemo@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MTLDemo@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the MTLDemo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs MTLDemo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls MTLDemo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mobile_app_ionic\mtlDemo\npm-debug.log

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
@ishumt,

Apps run on devices use `prod` builds, so they use the `Angular` `ngc` compiler. Basically, those errors are errors in your code. You need to fix them. `ngc` is really strict. Please look at the error messages and modify the code as needed. For additional help, please check out our [Ionic Forum](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA).

Thanks,
Dan
