### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined [0.0.42]

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#357]
Hey,

When I run "ionic serve", with the last build script 0.0.42, after around 10-20 sass changes and successful reload of the server, the server itself breaks. No big deal, could restart it, just wanted to let you know.

[18:45:05]  build finished in 28.25 s 

/myproject/node_modules/tiny-lr/src/server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
    at Server.error (/myproject/node_modules/tiny-lr/src/server.js:266:52)
    at Socket.<anonymous> (/myproject/node_modules/tiny-lr/src/server.js:217:22)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
    at Socket._destroy (net.js:480:3)
    at WriteWrap.afterWrite (net.js:765:10)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "[object Object]"
npm ERR! node v5.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! myproject@ ionic:serve: `ionic-app-scripts serve "[object Object]"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myproject@ ionic:serve script 'ionic-app-scripts serve "[object Object]"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flusterbeta package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "[object Object]"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myproject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myproject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /myproject/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

**Comment by karansharma27** [comment]
Did you get any solution, because I am facing the same problem too..

**Comment by peterpeterparker** [comment]
Actually I didn't made that much scss changes the past days/weeks.

But the same behavior kind of happens too when I do many typescript changes in a row, after a while, the ionic serve just hang on webpack ...

     [14:44:46]  build started ... 
     [14:44:46]  transpile update started ... 
     [14:44:46]  transpile update finished in 91 ms 
     [14:44:46]  webpack started ... 
     [14:44:46]  webpack started ... 

... and nothing, no "build finished", server has to be restarted

**Comment by danbucholtz** [comment]
@peterpeterparker,

Are you still seeing this issue? Is it a major drain on productivity?

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz sure close it for now. As I said, it appears when I did multiple changes in a row, which I do not do anymore these days. Will create a new task if I face it again in the future, thx

**Comment by nagarajns** [comment]
I am also getting this error

**Comment by danbucholtz** [comment]
@nagarajns,

How can I reproduce this? Same steps as @peterpeterparker?

Thanks,
Dan

**Comment by juanpablodelatorre** [comment]
This happens to me randomly. Last time it happened suddenly a couple of minutes after I ran `ionic serve`. Not really a productivity issue for me, but it may affect others.

````
[03:41:08] lint finished in 4.74 s

/home/user/projects/project/node_modules/tiny-lr/src/server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^
TypeError: Cannot read property 'message' of undefined
    at Server.error (/home/user/projects/project/node_modules/tiny-lr/src/server.js:266:52)
    at Socket.<anonymous> (/home/user/projects/project/node_modules/tiny-lr/src/server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:481:13)
    at Socket._destroy (net.js:522:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:816:10)
````

**Comment by vivekjoshi225** [comment]
With me, this happens every single time. :(
Has anyone explicitly solved this ?

Thanks.

**Comment by nileshzala005** [comment]
Error: Uncaught (in promise): TypeError: Cannot read property 'message' of undefined
TypeError: Cannot read property 'message' of undefined
    at http://localhost:8100/build/14.js:126:34
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at http://localhost:8100/build/polyfills.js:3:20273
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at XMLHttpRequest.v (http://localhost:8100/build/polyfills.js:2:27893)


I am facing same issue .serve stopped after error.
