### ISSUE TITLE
sudo ionic serve --lab not working 0.0.44

### ISSUE THREAD

**Issue by CarlRyds** [driftyco/ionic-app-scripts#413]
#### Short description of the problem:

sudo ionic serve --lab not working

#### What behavior are you expecting?

The app to build and open the --lab page

**Which @ionic/app-scripts version are you using?**

0.0.44 

**output**

```
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

> ionic-hello-world@ ionic:serve /Users/Carl/CraftingCoach
> ionic-app-scripts serve "--lab"

[22:57:39]  ionic-app-scripts 0.0.44 
[22:57:39]  watch started ... 
[22:57:39]  build dev started ... 
[22:57:39]  clean started ... 
[22:57:39]  clean finished in 1 ms 
[22:57:39]  copy started ... 
[22:57:39]  transpile started ... 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--" "--lab"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--lab"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--lab"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--lab"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Carl/CraftingCoach/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve
Carls-MacBook:CraftingCoach Carl$ 
```

**Comment by CarlRyds** [comment]
[npm-debug.log.zip](https://github.com/driftyco/ionic-app-scripts/files/596122/npm-debug.log.zip)

**Comment by kesozjura** [comment]
We have this issue without any argument, just 'ionic serve'. Sometimes it is transpiled successfully, but in browser console there is an error 'GET http://0.0.0.0:35729/livereload.js?snipver=1 net::ERR_ADDRESS_INVALID'

**Comment by dylanvdmerwe** [comment]
@danbucholtz isn't this sorted in 0.45?

**Comment by danbucholtz** [comment]
@dylanvdmerwe, I believe it is if you update to the latest CLI.

`npm install ionic@latest`

Thanks,
Dan

**Comment by CarlRyds** [comment]
Yep, all fixed, thanks guys :)
