### ISSUE TITLE
npm run build -> Missing Script: build

### ISSUE THREAD

**Issue by zishor** [driftyco/ionic-app-scripts#417]
Hi, after updating to "@ionic/app-scripts": "0.0.44" from 0.0.39 the npm run build fails with 

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--rollup' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /Users/frank.schmitz/git/roxx-ionic
6 error Darwin 16.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--rollup"
8 error node v6.5.0
9 error npm  v3.10.3
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

`

ionic build and ionic serve is all fine. 

Any ideas what I might be doing wrong? 

Thx in advance F-

**Comment by zishor** [comment]
Ok found the issue:

In your Blog http://blog.ionic.io/improvements-to-ionic-build-process/ you mention 

> Update the project’s package.json file’s script section to look like this:
`"scripts" : {
"ionic:build": "ionic-app-scripts build",
"ionic:serve": "ionic-app-scripts serve"
}`

after changing to 

`"scripts": {
    "build": "ionic-app-scripts build",
    "serve": "ionic-app-scripts serve"
  }`

The build runs again
