### ISSUE TITLE
Ionic 2 project working fine in browser but will not build for Android

### ISSUE THREAD

**Issue by wind13** [driftyco/ionic-app-scripts#493]
#### Short description of the problem:
When I develop with "ionic serve", the app works fine. 

But when I run "ionic build android", then got errors. I don't know why, it works fine in browser but failed in build.

My problem just like [this](http://stackoverflow.com/questions/40345357/ionic-2-project-working-fine-in-browser-but-will-not-build-for-ios){:target="_blank"} 

#### What behavior are you expecting?
I think if working fine in browser, it should build fine also.

If something not right, please show error in browser when developing.

**Steps to reproduce:**
1.  ionic serve
2. works fine in browser
3. ionic build android

Got errors.

Code is like this:
```javascript
import { Component } from '@angular/core';

import { NavController, ModalController } from 'ionic-angular';
import { FormBuilder, Validators, FormGroup} from '@angular/forms';

import { TabsPage } from '../tabs/tabs';
import { NetSettingPage } from '../net-setting/net-setting';

@Component({
  selector: 'page-login',
  templateUrl: 'login.html'
})
export class LoginPage {

  loginForm: FormGroup;

  constructor(form: FormBuilder, public navCtrl: NavController, public modalCtrl: ModalController) {
    this.loginForm = form.group({
        'username': ['', Validators.compose([Validators.required, Validators.minLength(4)])],
        'password': ['', Validators.compose([Validators.required, Validators.minLength(4)])],
        'rememberMe': [false]
    });
  }

  login(evt,username,password,rememberMe) {
    console.debug("do login...");
    this.navCtrl.setRoot(TabsPage);
  }

  netSetting() {
    console.debug("do net setting...");
    let modal = this.modalCtrl.create(NetSettingPage);
    modal.present();
  }
}

```

Error is like below:
```shell
[23:48:19]  ionic-app-scripts 0.0.39
[23:48:19]  build prod started ...
[23:48:19]  clean started ...
[23:48:19]  clean finished in 4 ms
[23:48:19]  copy started ...
[23:48:19]  ngc started ...
[23:48:20]  copy finished in 662 ms
[23:48:20]  lint started ...
[23:48:22]  lint finished in 2.29 s
[23:48:35]  Error: Error at /Users/samliu/gits/jing-xi-h5/.tmp/pages/login/login.ngfactory.ts:1054:68
[23:48:35]  Property 'username' does not exist on type 'LoginPage'.
[23:48:35]  Error at /Users/samliu/gits/jing-xi-h5/.tmp/pages/login/login.ngfactory.ts:1054:90
[23:48:35]  Property 'password' does not exist on type 'LoginPage'.
[23:48:35]  Error at /Users/samliu/gits/jing-xi-h5/.tmp/pages/login/login.ngfactory.ts:1054:112
[23:48:35]  Property 'rememberMe' does not exist on type 'LoginPage'.


[23:48:35]  Error at /Users/samliu/gits/jing-xi-h5/.tmp/pages/net-setting/net-setting.ngfactory.ts:1054:69


[23:48:35]  Property 'remote' does not exist on type 'NetSettingPage'.
[23:48:35]  Error at /Users/samliu/gits/jing-xi-h5/.tmp/pages/net-setting/net-setting.ngfactory.ts:1054:89
[23:48:35]  Property 'local' does not exist on type 'NetSettingPage'.
[23:48:35]  Error at /Users/samliu/gits/jing-xi-h5/.tmp/pages/net-setting/net-setting.ngfactory.ts:1054:108
[23:48:35]  Property 'isRemote' does not exist on type 'NetSettingPage'.
[23:48:35]  Error at /Users/samliu/gits/jing-xi-h5/.tmp/app/app.module.ngfactory.ts:443:133
[23:48:35]  Argument of type 'IonicErrorHandler' is not assignable to parameter of type 'ErrorHandler'.
[23:48:35]  Property 'handleError' is missing in type 'IonicErrorHandler'.
[23:48:35]  ngc failed
[23:48:35]  ionic-app-script task: "build"
[23:48:35]  Error: Error

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/samliu/gits/jing-xi-h5/npm-debug.log
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by wind13** [comment]
Fixed. Cause the login(evt,username,password,rememberMe) function params wrong. 

Remove unnecessary params it build works.
