### ISSUE TITLE
Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.

### ISSUE THREAD

**Issue by bassem00** [driftyco/ionic-app-scripts#509]
#### Short description of the problem:
 I created my project in windows, now when i switched it to work with antergos i can't serve it. But if i create a new project it works without any problems.

**Steps to reproduce:**
1. create a project in windows 10 envirennement.
2. moved the project to 'Antergos'
3. run 'ionic serve' or 'ionic run android' gets errors.

**using ionic 2.1.14**

** Content of npm-debug.log **
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'ionic:serve', '--' ]
> 2 info using npm@4.0.3
> 3 info using node@v7.2.0
> 4 verbose run-script [ 'preionic:serve', 'ionic:serve', 'postionic:serve' ]
> 5 info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
> 6 silly lifecycle ionic-hello-world@~preionic:serve: no script for preionic:serve, continuing
> 7 info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@
> 8 verbose lifecycle ionic-hello-world@~ionic:serve: unsafe-perm in lifecycle true
> 9 verbose lifecycle ionic-hello-world@~ionic:serve: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/bhp/developpement/ionicv2/test0/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> 10 verbose lifecycle ionic-hello-world@~ionic:serve: CWD: /home/bhp/developpement/ionicv2/test0
> 11 silly lifecycle ionic-hello-world@~ionic:serve: Args: [ '-c', 'ionic-app-scripts serve' ]
> 12 silly lifecycle ionic-hello-world@~ionic:serve: Returned: code: 1  signal: null
> 13 info lifecycle ionic-hello-world@~ionic:serve: Failed to exec ionic:serve script
> 14 verbose stack Error: ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:885:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 15 verbose pkgid ionic-hello-world@
> 16 verbose cwd /home/bhp/developpement/ionicv2/test0
> 17 error Linux 4.8.11-1-ARCH
> 18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "ionic:serve" "--"
> 19 error node v7.2.0
> 20 error npm  v4.0.3
> 21 error code ELIFECYCLE
> 22 error ionic-hello-world@ ionic:serve: `ionic-app-scripts serve`
> 22 error Exit status 1
> 23 error Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the ionic-hello-world package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     ionic-app-scripts serve
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs ionic-hello-world
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls ionic-hello-world
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by bassem00** [comment]
I solved this by running 'npm rebuild node-sass'
