### ISSUE TITLE
Error when running bundle step after upgrading to 0.0.47

### ISSUE THREAD

**Issue by bytenik** [driftyco/ionic-app-scripts#570]
When building using 0.0.47, I now get the following error:

```
[09:56:08]  ionic-app-scripts 0.0.47
[09:56:08]  webpack started ...
TypeError: Cannot read property 'fileCache' of undefined
    at Object.getIonicEnvironmentPlugin (C:\Users\bytenik\AppData\Roaming\npm\node_modules\@ionic\app-scripts\dist\webpack\ionic-webpack-factory.js:7:73)
    at Object.<anonymous> (C:\Users\bytenik\Dropbox\Projects\BallStreetApp\node_modules\@ionic\app-scripts\config\webpack.config.js:34:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

As near as I can tell, this is due to the fact that `context` is undefined because the `setContext` function from `util/helpers` is never being called. If I stick an import line for `setContext` at the top of `webpack.ts`, and then, as the first line in `webpack` from `webpack.ts` I write `setContext(context);`, the build runs just fine.

I'm not sure how I'm the only one hitting into this issue, though, so I'm confused.

**Comment by danbucholtz** [comment]
@bytenik,

You're probably the only one running `webpack` in a standalone fashion. I don't recommend doing this. I will revisit the docs and isolate the tasks that can be run independently.

Thanks,
Dan

**Comment by bytenik** [comment]
This happens even if I run through a normal build. I ran webpack alone just to isolate the stack trace.

**Comment by bytenik** [comment]
Well, killing node_modules and reinstalling made that error go away (except for when if run standalone).

**Comment by danbucholtz** [comment]
This is resolved now. This being the documentation, not running `webpack` in a standalone fashion.

Thanks,
Dan
