### ISSUE TITLE
ionic serve not working simultaneously in 2 projects

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-app-scripts#571]
#### Short description of the problem:
ionic serve not working if already running in other project. Even changing port is not working `ionic serve --port=8080`

#### What behavior are you expecting?
ionic serve should serve independently of other projects. if port is busy, start on next available port.

**Steps to reproduce:**
1. Create two Ionic 2 projects
2. Try `ionic serve` on both projects
3. It will work on one project only
4. `ionic serve --port=8080` is also not working

```
Anku@Ankushs-MacBook-Pro:ionic-conference-app$ ionic serve

> ionic-conference-app@ ionic:serve /Users/Anku/Documents/IdeaProjects/ionic-conference-app
> ionic-app-scripts serve

[10:14:12]  ionic-app-scripts 0.0.47 
[10:14:12]  watch started ... 
[10:14:12]  build dev started ... 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ionic:serve" "--"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic-conference-app@ ionic:serve: `ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-conference-app@ ionic:serve script 'ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-conference-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-conference-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-conference-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Anku/Documents/IdeaProjects/ionic-conference-app/npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve

```

**Which @ionic/app-scripts version are you using?**
`ionic-app-scripts 0.0.47`

**Comment by danbucholtz** [comment]
This is already fixed in `nightly`. `npm install @ionic/app-scripts@nightly`. It'll be in `0.0.48`, which I am shipping soon just wrapping up one for fix. Closing this as it's a duplicate.

Thanks,
Dan
