### ISSUE TITLE
watch don't work when I use a custom copy.config.js

### ISSUE THREAD

**Issue by twincle** [driftyco/ionic-app-scripts#575]
#### Short description of the problem:
watch don't work when I use a custom copy.config.js under "ionic serve"
if I extend the default watch.config.js to be a custom watch.config.js, there is an error in the console

**Steps to reproduce:**
1. use a custom copy.config.js, there's no watch log
```
D:\Code\test\ionic-3rd>ionic serve

> ionic-hello-world@ ionic:serve D:\Code\test\ionic-3rd
> ionic-app-scripts serve

[02:10:06]  ionic-app-scripts 0.0.47
[02:10:07]  watch started ...
[02:10:07]  build dev started ...
[02:10:07]  clean started ...
[02:10:07]  clean finished in 53 ms
[02:10:07]  copy started ...
[02:10:07]  transpile started ...
[02:10:20]  transpile finished in 12.60 s
[02:10:20]  webpack started ...
[02:10:27]  copy finished in 19.93 s
[02:10:57]  webpack finished in 37.00 s
[02:10:57]  sass started ...
[02:11:04]  sass finished in 6.95 s
[02:11:04]  build dev finished in 56.70 s
[02:11:04]  dev server running: http://localhost:8100/
```

2. if I extend the default watch.config.js to be a custom watch.config.js, there is an error in the console
```
D:\Code\test\ionic-3rd>ionic serve

> ionic-hello-world@ ionic:serve D:\Code\test\ionic-3rd
> ionic-app-scripts serve

[02:18:42]  ionic-app-scripts 0.0.47
[02:18:43]  watch started ...
[02:18:43]  build dev started ...
[02:18:43]  clean started ...
[02:18:43]  clean finished in 40 ms
[02:18:43]  copy started ...
[02:18:43]  transpile started ...
[02:18:54]  transpile finished in 10.38 s
[02:18:54]  webpack started ...
[02:19:00]  copy finished in 16.45 s
[02:19:22]  webpack finished in 28.72 s
[02:19:22]  sass started ...
[02:19:27]  sass finished in 4.81 s
[02:19:27]  build dev finished in 44.09 s
There was an error in config file "D:\Code\test\ionic-3rd\config\watch.config.js". Using defaults instead.
TypeError: Cannot read property 'rootDir' of undefined
    at Object.getUserConfigFile (D:\Code\test\ionic-3rd\node_modules\@ionic\app-scripts\dist\util\config.js:96:35)
    at Object.copyConfigToWatchConfig (D:\Code\test\ionic-3rd\node_modules\@ionic\app-scripts\dist\copy.js:236:31)
    at Object.<anonymous> (D:\Code\test\ionic-3rd\node_modules\@ionic\app-scripts\config\watch.config.js:16:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
[02:19:27]  dev server running: http://localhost:8100/
```

```
// custom copy.config.js

let origin = require('@ionic/app-scripts/config/copy.config');

origin.copyFontAwesome = {
  src: ['{{ROOT}}/node_modules/font-awesome/fonts/*'],
  dest: '{{WWW}}/fonts'
};
origin.copyEmojioneCSS = {
  src: ['{{ROOT}}/node_modules/emojione/assets/css/emojione.css'],
  dest: '{{BUILD}}'
};
origin.copyEmojionePNG = {
  src: ['{{ROOT}}/node_modules/emojione/assets/png/*'],
  dest: '{{WWW}}/assets/emojione'
};

module.exports = origin;
```

```
// custom watch.config.js

let origin = require('@ionic/app-scripts/config/watch.config');

module.exports = origin;
```

**Which @ionic/app-scripts version are you using?**
0.0.47

**Comment by danbucholtz** [comment]
This is a known issue. Sorry! Please install `npm install @ionic/app-scripts@nightly` and it's fixed.

I am going to close since this is a duplicate.

Thanks,
Dan
