### ISSUE TITLE
`ionic serve` along with `ionic run <platform>`

### ISSUE THREAD

**Issue by pacMakaveli** [driftyco/ionic-app-scripts#576]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

In `0.0.0.45` I was able to run `ionic serve -l -c` along with `ionic run ios -l -c` which would give me a working live reload app on the phone while also showing the changes in the browser.
This was the only way to make the Live Reload work on device.

With `0.0.0.47` I cannot run them at the same time as I get this error: 

```
> @ ionic:serve /Users//////--
> ionic-app-scripts serve "-c" "-l"

[06:15:05]  ionic-app-scripts 0.0.47
[06:15:05]  watch started ...
[06:15:05]  build dev started ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:53703
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users//.nvm/versions/node/v6.3.0/bin/node" "/Users//.nvm/versions/node/v6.3.0/bin/npm" "run" "ionic:serve" "--" "-c" "-l"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! smartedi@ ionic:serve: `ionic-app-scripts serve "-c" "-l"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the@ ionic:serve script 'ionic-app-scripts serve "-c" "-l"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "-c" "-l"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

Obviously, I know why it errors. However, I don't know why the behaviour changed. Is it a bug or intentional?

#### What behavior are you expecting?

I should be able to run `ionic serve -l -c` along with `ionic run ios -l -c` without any errors. I would expect the latter to dynamically assign the next available port like in `0.0.0.45`

**Steps to reproduce:**
1. ionic serve -l -c
2. ionic run ios -l -c --device

**Which @ionic/app-scripts version are you using?**

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.3.0
Xcode version: Xcode 8.2 Build version 8C38
```

I think this behaviour was introduced with https://github.com/driftyco/ionic-app-scripts/commit/d6de4132247af41a52e291f15f91cc4930404092 ..

**Comment by loicfavory** [comment]
Work for me, using the address of the dev server

```
ionic run android -l

[09:20:24]  ionic-app-scripts 0.0.47-201612152207 
[09:20:24]  watch started ... 
[09:20:24]  build dev started ... 
[09:20:24]  clean started ... 
[09:20:24]  clean finished in 5 ms 
[09:20:24]  copy started ... 
[09:20:24]  transpile started ... 
[09:20:27]  transpile finished in 2.68 s 
[09:20:27]  webpack started ... 
[09:20:27]  copy finished in 2.86 s 
[09:20:35]  webpack finished in 8.05 s 
[09:20:35]  sass started ... 
[09:20:37]  sass finished in 1.96 s 
[09:20:37]  build dev finished in 12.72 s 
[09:20:37]  watch ready in 12.78 s 
[09:20:37]  dev server running: http://192.168.2.33:8000/ 
```

If I use http://192.168.2.33:8000/ I have the livereload on my browser

**Comment by pacMakaveli** [comment]
@loicfavory It seems you're right. I didn't think that the dev server is viewable in the browser but just an address where the app connects. Thanks!
