### ISSUE TITLE
Using --prod flag emits short error to main.js instead of the app code 

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-app-scripts#588]
#### Short description of the problem:

When running `ionic build --prod` instead of the app's js code some minimal minified js is outputted containing an error.  

The content of `main.js`:

```js
!function(r){function e(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return r[n].call(o.exports,o,o.exports,e),o.l=!0,o.exports}var t={};return e.m=r,e.c=t,e.i=function(r){return r},e.d=function(r,t,n){e.o(r,t)||Object.defineProperty(r,t,{configurable:!1,enumerable:!0,get:n})},e.n=function(r){var t=r&&r.__esModule?function(){return r.default}:function(){return r};return e.d(t,"a",t),t},e.o=function(r,e){return Object.prototype.hasOwnProperty.call(r,e)},e.p="",e(e.s=0)}([function(r,e){throw new Error("Module build failed: TypeError: Cannot set property 'sources' of undefined\n    at /Users/user/projects/Project/node_modules/@ionic/app-scripts/dist/webpack/loader-impl.js:35:37")}]);
//# sourceMappingURL=main.js.map
```

#### What behavior are you expecting?

Commands with the `--prod` flag works.

**Steps to reproduce:**
1. Run any ionic command with the `--prod` flag
2. Check out the content on `main.js` in the `www/build` folder.

**Which @ionic/app-scripts version are you using?** 0.0.48

Your system information:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by NoNameProvided** [comment]
The issue is related with the AOT as using only the `--aot` flag will yield this to the `main.js`: 

```
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.l = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// identity function for calling harmony imports with the correct context
/******/ 	__webpack_require__.i = function(value) { return value; };

/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};

/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};

/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports) {

eval("throw new Error(\"Module build failed: TypeError: Cannot set property 'sources' of undefined\\n    at /Users/attila/budacode/transfermarkt-mobile/node_modules/@ionic/app-scripts/dist/webpack/loader-impl.js:35:37\");\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/main.ts\n// module id = 0\n// module chunks = 0\n\n//# sourceURL=/user/projects/Project/transfermarkt-mobile/src/app/main.ts");

/***/ }
/******/ ]);
```

**Comment by rapropos** [comment]
Perhaps a dupe of #583?

**Comment by NoNameProvided** [comment]
Yes thanks! That did the trick for me!
