### ISSUE TITLE
Cannot find custom config file when using “ionic run android -s -c -r”

### ISSUE THREAD

**Issue by twincle** [driftyco/ionic-app-scripts#601]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Cannot find custom config file when using “ionic run android -s -c -r”
but when using "ionic build android" is fine

#### What behavior are you expecting?

**Steps to reproduce:**
1. i'm using copy and sass custom config file from font-awesome
2. wierd log in console

```
[17:35:52]  ionic-app-scripts 0.0.48
[17:35:52]  build dev started ...
[17:35:52]  clean started ...
[17:35:52]  clean finished in 21 ms
[17:35:52]  copy started ...
[17:35:52]  transpile started ...
Config file "D:\Code\test\ionic-doc-study\--" not found. Using defaults instead.
Config file "D:\Code\test\ionic-doc-study\--" not found. Using defaults instead.
[17:35:59]  transpile finished in 6.62 s
[17:35:59]  rollup started ...
[17:36:01]  copy finished in 9.26 s
[17:37:03]Config file "D:\Code\test\ionic-doc-study\-c" not found. Using defaults instead.
  rollup finished in 64.34 s
[17:37:03]  sass started ...
[17:37:03]  sass: D:/Code/test/ionic-doc-study/src/theme/variables.scss, line: 75
            File to import not found or unreadable: font-awesome Parent style sheet:
            D:/Code/test/ionic-doc-study/src/theme/variables.scss

      L74:  // Font Awesome
      L75:  @import "font-awesome";

[17:37:03]  sass failed
[17:37:03]  ionic-app-script task: "build"
[17:37:03]  TypeError: error.message.indexOf is not a function
TypeError: error.message.indexOf is not a function
    at handleDeprecations (D:\Code\test\ionic-doc-study\node_modules\@ionic\app-scripts\dist\build.js:32:49)
    at D:\Code\test\ionic-doc-study\node_modules\@ionic\app-scripts\dist\build.js:26:9
    at process._tickCallback **(internal/process/next_tick.js:103:7)**
```

**Which @ionic/app-scripts version are you using?**
0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by twincle** [comment]
can anyone help me? please

**Comment by danbucholtz** [comment]
@twincle,

Can you upload a minimal example repo demonstrating the issue? I'll take a look.

Thanks,
Dan
