### ISSUE TITLE
Using Webpack breaks the app

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-app-scripts#619]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
If I want to use Webpack for builds, I get the following error once the app is started with `npm run ionic:serve`:
```text
main.js:34511 Uncaught Error: moduleId should be a string in "ObservationMetadataComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
    at componentModuleUrl (http://localhost:8100/build/main.js:34511:15)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:8100/build/main.js:33863:25)
    at CompileMetadataResolver._loadDirectiveMetadata (http://localhost:8100/build/main.js:33799:42)
    at Array.map (native)
    at CompileMetadataResolver.loadNgModuleMetadata (http://localhost:8100/build/main.js:33980:68)
    at RuntimeCompiler._loadModules (http://localhost:8100/build/main.js:50670:41)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:8100/build/main.js:50640:35)
    at RuntimeCompiler.compileModuleAsync (http://localhost:8100/build/main.js:50630:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8100/build/main.js:36206:25)
    at Object.<anonymous> (http://localhost:8100/build/main.js:140737:6)
```

#### What behavior are you expecting?
The app should work.

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
@rolandjitsu,

Please provide a repo to reproduce the issue. At first glance, it seems like the developer is incorrectly distributing their lib.

Thanks,
Dan

**Comment by rolandjitsu** [comment]
@danbucholtz Unfortunately I cannot share code, I signed a NDA. But true, it's actually one of my own packages :) Give me a few minutes to double check that.

**Comment by rolandjitsu** [comment]
Yes, it was because of my own package. A `moduleId` slipped and it never failed when I was using Rollup.
