### ISSUE TITLE
Barrell stopped working after update to 1.0.0.

### ISSUE THREAD

**Issue by kleeb** [driftyco/ionic-app-scripts#629]
#### Short description of the problem:
After upgrading to 1.0.0 and building the project with --prod flag I am getting this error:

```
[16:26:27]  rollup failed: 'FormInput' is not exported by src/datas/config/form-input.ts (imported by 
            src/components/module-components/module-forms-component/module-forms-input.ts). For help fixing this error 
            see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module 
[16:26:27]  ionic-app-script task: "build" 
[16:26:27]  Error: 'FormInput' is not exported by src/datas/config/form-input.ts (imported by 
            src/components/module-components/module-forms-component/module-forms-input.ts). For help fixing this error 
            see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module 
Error: 'FormInput' is not exported by src/datas/config/form-input.ts (imported by src/components/module-components/module-forms-component/module-forms-input.ts). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
    at Module.trace (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:7752:29)
    at ModuleScope.findDeclaration (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:7374:22)
    at Scope.findDeclaration (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:5361:39)
    at Node.bind (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:6529:29)
    at node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:5155:50
    at Node.eachChild (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:5172:5)
    at Node.bind (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:5155:7)
    at Node.bind (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:6931:53)
    at node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:5155:50
    at Node.eachChild (node_modules/@ionic/app-scripts/node_modules/rollup/dist/rollup.js:5172:5)
```

Running without --prod works good. Looks like for some reason Rollup is not recognizing the export.

**Which @ionic/app-scripts version are you using?**
1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

in 0.0.48 there is no such problem.

**Comment by danbucholtz** [comment]
@kleeb,

This appears to be an issue with your code that Rollup is reporting that it didn't previously.

Can you investigate? I'll re-open if needed.

Thanks,
Dan

**Comment by kleeb** [comment]
changed problematic interfaces to classes, and rollup finally compiled the code
don't know why is it happening though...
