### ISSUE TITLE
Rollup failed with v1.0.0 of --prod mode

### ISSUE THREAD

**Issue by iron9light** [driftyco/ionic-app-scripts#675]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
`ionic-app-scripts build --prod --bundler rollup` failed with error:
```
[13:48:41]  rollup failed: 'Observer' is not exported by node_modules\rxjs\Observer.js (imported by
            src\modules\@ngrx\effects\effects-subscription.ts). For help fixing this error see
            https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
[13:48:41]  ionic-app-script task: "build"
[13:48:41]  Error: 'Observer' is not exported by node_modules\rxjs\Observer.js (imported by
            src\modules\@ngrx\effects\effects-subscription.ts). For help fixing this error see
            https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: 'Observer' is not exported by node_modules\rxjs\Observer.js (imported by src\modules\@ngrx\effects\effects-subscription.ts). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
    at Module.trace (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:7752:29)
    at ModuleScope.findDeclaration (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:7374:22)
    at Scope.findDeclaration (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:5361:39)
    at Identifier.bind (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:6529:29)
    at D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:5155:50
    at UnaryExpression.eachChild (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:5172:5)
    at UnaryExpression.bind (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:5155:7)
    at UnaryExpression.bind (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:6931:53)
    at D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:5155:50
    at BinaryExpression.eachChild (D:\10kplus_sandbox\node_modules\rollup\dist\rollup.js:5172:5)
```
This error only shows with v1.0.0 but works fine with v0.0.48
And `ionic-app-scripts build --prod`, `ionic-app-scripts serve` even `ionic-app-scripts serve --bundler rollup` with script@1.0.0 work with no problem.

```
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/material": "2.0.0-beta.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "@ngrx/core": "1.2.0",
    "@ngrx/store": "2.2.1",
    "@types/jquery": "2.0.39",
    "chart.js": "2.4.0",
    "immutable": "3.8.1",
    "ionic-angular": "2.0.0-rc.5",
    "ionic-native": "2.2.16",
    "ionicons": "3.0.0",
    "jquery": "3.1.1",
    "mdi": "1.8.36",
    "moment": "2.17.1",
    "pouchdb": "6.1.1",
    "pouchdb-adapter-cordova-sqlite": "2.0.2",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "sw-toolbox": "^3.4.0",
    "typescript": "2.0.10"
  },
```

**Which @ionic/app-scripts version are you using?**
1.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

**Comment by danbucholtz** [comment]
@iron9light,

Can you create a minimal example repository so I can recreate and fix this?

Thanks,
Dan

**Comment by iron9light** [comment]
@danbucholtz https://github.com/iron9light/bugs/tree/ionic-app-scripts/675

**Comment by iron9light** [comment]
Update to ionic scripts v1.0.1. Got this new error below.
```
[17:14:35]  rollup failed: A module cannot import itself
[17:14:35]  ionic-app-script task: "build"
[17:14:35]  Error: A module cannot import itself
Error: A module cannot import itself
    at error (E:\GitHub\bugs\675\node_modules\rollup\dist\rollup.js:170:12)
    at Module.error$1 [as error] (E:\GitHub\bugs\675\node_modules\rollup\dist\rollup.js:7997:2)
    at E:\GitHub\bugs\675\node_modules\rollup\dist\rollup.js:9578:14
```

https://github.com/iron9light/bugs/tree/1637b6320f3c90e1846faac5b626d7f3cd7c4e2a/675

**Comment by iron9light** [comment]
Update to ionic scripts **v1.1.0**.
`ionic-app-scripts build --prod --bundler rollup` failed with the same error as v1.0.1.
```
[17:14:35]  rollup failed: A module cannot import itself
[17:14:35]  ionic-app-script task: "build"
[17:14:35]  Error: A module cannot import itself
Error: A module cannot import itself
    at error (E:\GitHub\bugs\675\node_modules\rollup\dist\rollup.js:170:12)
    at Module.error$1 [as error] (E:\GitHub\bugs\675\node_modules\rollup\dist\rollup.js:7997:2)
    at E:\GitHub\bugs\675\node_modules\rollup\dist\rollup.js:9578:14
```

And `ionic-app-scripts build --prod` works again.

https://github.com/iron9light/bugs/tree/c69b79fc9a9a037c9df3afd75a0522e425916200/675

**Comment by danbucholtz** [comment]
Sorry, those are Rollup errors. Can you figure out what the issue is and create an entry on the Rollup repository? There isn't anything we can do to fix them.

Thanks,
Dan

**Comment by iron9light** [comment]
@danbucholtz As you can see, I only changed ionic-scripts version and got different errors. Do you mean this is cause by different version of Rollup?
I've no experience of Rollup at all. What issue of Rollup do you think?

**Comment by danbucholtz** [comment]
We did upgrade the Rollup version to the latest since it had a bunch of bug fixes in it. Perhaps it introduces this bug? I'm not sure.

Thanks,
Dan

**Comment by iron9light** [comment]
@danbucholtz I've share the sample code. It's not depend on Rollup directly, but via ionic-scripts.
If it's a bug of Rollup, I think ionic-scripts@1.0.0 and above version depend on different version of Rollup. Or it should be a bug of ionic-scripts. Since nothing changed except ionic-scripts.
