### ISSUE TITLE
error with --prod stop at ngc

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic-app-scripts#784]
u can check this repo
https://github.com/fundo90/ionic2-starter-admin/tree/6ec9227554c234b019741ba89857c1df45452ce4

first, let me thell u what did I do.
something in `app.module.ts` is duplicated
between `declarations` and `entryComponents`

so I make 2 array named `entry` and `extra`
u can find out [here](https://github.com/fundo90/ionic2-starter-admin/blob/6ec9227554c234b019741ba89857c1df45452ce4/src/imports/app.ts#L17-L28)

and let the `declarations` to be `App.entry.concat(App.extra)`
u can find out [here](https://github.com/fundo90/ionic2-starter-admin/blob/6ec9227554c234b019741ba89857c1df45452ce4/src/app/app.module.ts#L7)

the problem is when I run `npm run ionic:build --prod`
it will show error like
```
➜  ionic2-starter-admin git:(master) npm run build --prod

> ionic2admin@ build /Users/yozman/fundo90/ionic2-starter-admin
> ionic-app-scripts build

[02:36:03]  ionic-app-scripts 1.1.4 
[02:36:03]  build prod started ... 
[02:36:03]  clean started ... 
[02:36:03]  clean finished in 3 ms 
[02:36:03]  copy started ... 
[02:36:03]  ngc started ... 
[02:36:04]  build prod failed: Cannot determine the module for class AppComponent in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/app/app.component.ts! Cannot determine the module for class 
            LayoutComponent in /Users/yozman/fundo90/ionic2-starter-admin/src/components/layout/layout.ts! Cannot 
            determine the module for class NavContentComponent in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/components/nav-content/nav-content.ts! Cannot determine the 
            module for class NavHeaderComponent in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/components/nav-header/nav-header.ts! Cannot determine the 
            module for class MainPage in /Users/yozman/fundo90/ionic2-starter-admin/src/pages/main/main.ts! Cannot 
            determine the module for class Link in /Users/yozman/fundo90/ionic2-starter-admin/src/pipes/link.ts! Cannot 
            determine the module for class Timestamp in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/pipes/timestamp.ts! 
[02:36:04]  ionic-app-script task: "build" 
[02:36:04]  Error: Cannot determine the module for class AppComponent in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/app/app.component.ts! Cannot determine the module for class 
            LayoutComponent in /Users/yozman/fundo90/ionic2-starter-admin/src/components/layout/layout.ts! Cannot 
            determine the module for class NavContentComponent in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/components/nav-content/nav-content.ts! Cannot determine the 
            module for class NavHeaderComponent in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/components/nav-header/nav-header.ts! Cannot determine the 
            module for class MainPage in /Users/yozman/fundo90/ionic2-starter-admin/src/pages/main/main.ts! Cannot 
            determine the module for class Link in /Users/yozman/fundo90/ionic2-starter-admin/src/pipes/link.ts! Cannot 
            determine the module for class Timestamp in 
            /Users/yozman/fundo90/ionic2-starter-admin/src/pipes/timestamp.ts! 
Error: Cannot determine the module for class AppComponent in /Users/yozman/fundo90/ionic2-starter-admin/src/app/app.component.ts!
Cannot determine the module for class LayoutComponent in /Users/yozman/fundo90/ionic2-starter-admin/src/components/layout/layout.ts!
Cannot determine the module for class NavContentComponent in /Users/yozman/fundo90/ionic2-starter-admin/src/components/nav-content/nav-content.ts!
Cannot determine the module for class NavHeaderComponent in /Users/yozman/fundo90/ionic2-starter-admin/src/components/nav-header/nav-header.ts!
Cannot determine the module for class MainPage in /Users/yozman/fundo90/ionic2-starter-admin/src/pages/main/main.ts!
Cannot determine the module for class Link in /Users/yozman/fundo90/ionic2-starter-admin/src/pipes/link.ts!
Cannot determine the module for class Timestamp in /Users/yozman/fundo90/ionic2-starter-admin/src/pipes/timestamp.ts!
    at analyzeAndValidateNgModules (/Users/yozman/fundo90/ionic2-starter-admin/node_modules/.2.4.8@@angular/compiler/bundles/compiler.umd.js:24951:19)
    at AotCompiler.compileAll (/Users/yozman/fundo90/ionic2-starter-admin/node_modules/.2.4.8@@angular/compiler/bundles/compiler.umd.js:24672:22)
    at CodeGenerator.codegen (/Users/yozman/fundo90/ionic2-starter-admin/node_modules/.2.4.8@@angular/compiler-cli/src/codegen.js:30:14)
    at Object.runCodegen (/Users/yozman/fundo90/ionic2-starter-admin/node_modules/.1.1.4@@ionic/app-scripts/dist/aot/codegen/codegen-ng23plus.js:15:26)
    at Object.doCodegen (/Users/yozman/fundo90/ionic2-starter-admin/node_modules/.1.1.4@@ionic/app-scripts/dist/aot/codegen.js:8:31)
    at /Users/yozman/fundo90/ionic2-starter-admin/node_modules/.1.1.4@@ionic/app-scripts/dist/aot/aot-compiler.js:41:30
```

could you please fix it?

by the way
`ionic serve` and `npm run ionic:build` works well only trouble with `--prod` option.
and when I declare manually not use `Array.concat` it works well too

**Comment by yozman** [comment]
@danbucholtz 
could u please fix this?
now with 1.1.4
`providers` is works well with `[].concat(xxx, xxx)`
but `declarations` is still not work

**Comment by ryanemax** [comment]
Same ISSUE!
Why it will not build --prod when use the Array.concat?

**Comment by liangwenzhong** [comment]
any solution?

**Comment by liangwenzhong** [comment]
@yozman have u resolve this problem？

**Comment by ryanemax** [comment]
Maybe we should waiting ionic3.0, which have better strategy for @ngModule, and we could use webpack's LazyLoading after that.

**Comment by danbucholtz** [comment]
I'm not sure why it won't build, but it is likely do to NgModules requirement to be statically analyzable.

There isn't anything we can do here unfortunately. With Ionic 3 (coming out soon), the NgModule story should be simplified to a degree and it's rare you'll ever use `entryComponents`.

Thanks,
Dan

**Comment by yozman** [comment]
@danbucholtz 
could you please release v3-alpha ?

thanks,
rifle

**Comment by yozman** [comment]
hi, everybody
u can taste this feature with ionic3.0.0-beta.3

this is the example repo
[ionic2-starter-mobile](https://github.com/fundo90/ionic2-starter-mobile/tree/b53023d99e78e7b2b56ff4345555656b2de743b7)

![](https://cloud.githubusercontent.com/assets/11918866/24598590/bd916bd4-187e-11e7-87ee-ec8c8b62974d.png)
