### ISSUE TITLE
Production build fails, but normal build doesn't

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-app-scripts#786]
#### Short description of the problem:
`ionic build android` works.
`ionic build android --prod` fails, with this error:
```
[21:09:51]  build prod failed: Unexpected value 'ChartistModule' imported by the module 'AppModule' 
[21:09:51]  ionic-app-script task: "build" 
[21:09:51]  Error: Unexpected value 'ChartistModule' imported by the module 'AppModule' 
Error: Unexpected value 'ChartistModule' imported by the module 'AppModule'
    at D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:14675:33
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)
    at analyzeNgModules (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (D:\xampp\htdocs\qzzy\node_modules\@angular\compiler\bundles\compiler.umd.js:12704:20)
```

Note, this happens after adding[ this module](https://github.com/willsoto/angular2-chartist) to the build.

#### What behavior are you expecting?
Production build to work

**Steps to reproduce:**
1. Add this module - https://github.com/willsoto/angular2-chartist - see the installation guide
2. Import that module to your app
3. `ionic build android --prod`

**Which @ionic/app-scripts version are you using?**
```
 ordova CLI: 6.5.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by danbucholtz** [comment]
This is likely an issue with the third party lib.

Thanks,
Dan
