### ISSUE TITLE
Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol.

### ISSUE THREAD

**Issue by kleeb** [driftyco/ionic-app-scripts#815]
I am having app config, that is outside the bundle and loading in script tag before the bundle with some global variable like this:

```
var someVar = { ... };
```

Referencing it in app.module like this:

```
declare var someVar;
```

When I am getting data from it in app module, all works during the development build, when building the aot release I am getting:

```
[11:16:11]  build prod failed: Error encountered resolving symbol values statically. Reference to a local (non-exported) 
            symbol 'someVar'. Consider exporting the symbol (position 16:13 in the original .ts file), resolving 
            symbol firebaseConfig in .src/app/app.module.ts, resolving symbol AppModule in 
            .src/app/app.module.ts, resolving symbol AppModule in 
            .src/app/app.module.ts, resolving symbol AppModule in 
            .src/app/app.module.ts 
[11:16:11]  ionic-app-script task: "build" 
[11:16:11]  Error: Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 
            'someVar'. Consider exporting the symbol (position 16:13 in the original .ts file), resolving symbol 
            firebaseConfig in .src/app/app.module.ts, resolving symbol AppModule in 
            .src/app/app.module.ts, resolving symbol AppModule in 
            .src/app/app.module.ts, resolving symbol AppModule in 
            .src/app/app.module.ts 
Error: Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'someVar'. Consider exporting the symbol (position 16:13 in the original .ts file), resolving symbol firebaseConfig in .src/app/app.module.ts, resolving symbol AppModule in .src/app/app.module.ts, resolving symbol AppModule in .src/app/app.module.ts, resolving symbol AppModule in .src/app/app.module.ts
    at positionalError (.node_modules/@angular/compiler/bundles/compiler.umd.js:25944:39)
    at simplifyInContext (.node_modules/@angular/compiler/bundles/compiler.umd.js:25781:31)
    at StaticReflector.simplify (.node_modules/@angular/compiler/bundles/compiler.umd.js:25795:17)
    at StaticReflector.annotations (.node_modules/@angular/compiler/bundles/compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (.node_modules/@angular/compiler/bundles/compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (.node_modules/@angular/compiler/bundles/compiler.umd.js:18272:64)
    at addNgModule (.node_modules/@angular/compiler/bundles/compiler.umd.js:25053:62)
    at .node_modules/@angular/compiler/bundles/compiler.umd.js:25064:18
    at Array.forEach (native)
    at _createNgModules (.node_modules/@angular/compiler/bundles/compiler.umd.js:25063:30)
```

ionic 2.2.0
app-scripts 1.1.4
using rollup

**Comment by shawnlan** [comment]
Have you tried `export declare var someVar;`?

**Comment by kleeb** [comment]
Tried different things, always with some kind of error. Adding export ends up with:

```
Error encountered resolving symbol values statically. Only initialized variables and 
            constants can be referenced because the value of this variable is needed by the template compiler
```

looks like its more an Angular bug: https://github.com/angular/angular/issues/14323
