### ISSUE TITLE
Error: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by cjorasch** [driftyco/ionic-app-scripts#866]
#### Short description of the problem:

When building the app I get an error that terminates the build process

Error: Cannot read property 'filter' of undefined

#### What behavior are you expecting?

Ability to build the app.  The error started when I moved from 1.1.4 to 1.2.X

**Steps to reproduce:**
1.  ionic serve

```
[12:14:59]  ionic-app-scripts 1.2.5
[12:14:59]  watch started ...
[12:14:59]  build dev started ...
[12:14:59]  clean started ...
[12:14:59]  clean finished in 4 ms
[12:14:59]  copy started ...
[12:14:59]  transpile started ...
[12:15:04]  transpile finished in 5.21 s
[12:15:04]  preprocess started ...
[12:15:04]  deeplinks started ...
[12:15:05]  ionic-app-script task: "serve"
[12:15:05]  Error: Cannot read property 'filter' of undefined
Error: Cannot read property 'filter' of undefined
    at new BuildError (/Users/cjorasch/Projects/Meetings2/client/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/cjorasch/Projects/Meetings2/client/node_modules/@ionic/app-scripts/dist/preprocess.js:17:21
```

**Which @ionic/app-scripts version are you using?**

ionic-app-scripts 1.2.5

Builds succeeds with 1.1.4.  Upgrading to 1.2.0 results in the build error.  Error still exists in 1.2.5.
Same error with Ionic 2 and Ionic 3.0.0-beta.3

**Comment by danbucholtz** [comment]
This should be fixed in `nightly`. Can you please verify?

```
npm install @ionic/app-scripts@nightly
```

Thanks,
Dan

**Comment by cjorasch** [comment]
same issue

[13:19:09]  ionic-app-scripts 1.2.5-201703312015
[13:19:09]  watch started ...
[13:19:09]  build dev started ...
[13:19:09]  clean started ...
[13:19:09]  clean finished in 1 ms
[13:19:09]  copy started ...
[13:19:09]  transpile started ...
[13:19:15]  transpile finished in 5.35 s
[13:19:15]  preprocess started ...
[13:19:15]  deeplinks started ...
[13:19:15]  ionic-app-script task: "serve"
[13:19:15]  Error: Could not find IonicModule.forRoot call in "imports"
Error: Could not find IonicModule.forRoot call in "imports"
    at new BuildError (/Users/cjorasch/Projects/Meetings2/client/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/cjorasch/Projects/Meetings2/client/node_modules/@ionic/app-scripts/dist/preprocess.js:17:21

**Comment by cjorasch** [comment]
I was able to resolve the problem.

I had been defining the imports in an array:

```
const appImports = [
        BrowserModule,
        HttpModule,
        IonicModule.forRoot(M2App)
];

@NgModule({
    imports: appImports,
    bootstrap: appBootstrap,
    declarations: appDeclarations,
    entryComponents: appEntryComponents,
    providers: appProviders
})
```

When I defined them inline it started working.

```
@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        IonicModule.forRoot(M2App)
    ],
    bootstrap: appBootstrap,
    declarations: appDeclarations,
    entryComponents: appEntryComponents,
    providers: appProviders
})
```
