### ISSUE TITLE
tslint task is not using the version I state in package.json

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-app-scripts#886]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

It seems that there are some inconsistencies with `ionic-app-scripts lint` and the lint task that runs during a production build.

My `package.json`:
```json
{
	"name": "",
	"version": "0.0.0",
	"description": "",
	"keywords": [],
	"homepage": "",
	"author": {
		"name": "Roland Groza",
		"email": "rolandjitsu@gmail.com"
	},
	"scripts": {
		"ionic:build": "ionic-app-scripts build",
		"ionic:serve": "ionic-app-scripts serve",
		"ionic:clean": "ionic-app-scripts clean",
		"ionic:lint": "ionic-app-scripts lint"
	},
	"config": {
		"ionic_bundler": "rollup",
		"ionic_rollup": "./config/rollup.config.js",
		"ionic_copy": "./config/copy.config.js",
		"ionic_experimental_parse_deeplinks": true,
		"ionic_experimental_purge_decorators": true
	},
	"dependencies": {
		"@angular/animations": "4.0.0",
		"@angular/common": "4.0.0",
		"@angular/compiler": "4.0.0",
		"@angular/compiler-cli": "4.0.0",
		"@angular/core": "4.0.0",
		"@angular/forms": "4.0.0",
		"@angular/http": "4.0.0",
		"@angular/platform-browser": "4.0.0",
		"@angular/platform-browser-dynamic": "4.0.0",
		"@ionic-native/background-geolocation": "3.4.2",
		"@ionic-native/camera": "3.4.2",
		"@ionic-native/core": "3.4.2",
		"@ionic-native/firebase": "3.4.2",
		"@ionic-native/geolocation": "3.4.2",
		"@ionic-native/keyboard": "3.4.2",
		"@ionic-native/nfc": "3.4.2",
		"@ionic-native/splash-screen": "3.4.2",
		"@ionic-native/status-bar": "3.4.2",
		"@ionic/storage": "2.0.1",
		"core-js": "^2.4.1",
		"ionic-angular": "3.0.1",
		"ionicons": "3.0.0",
		"moment": "^2.18.1",
		"raven-js": "^3.14.0",
		"reflect-metadata": "^0.1.9",
		"rxjs": "5.1.1",
		"sw-toolbox": "3.6.0",
		"zone.js": "^0.8.5"
	},
	"devDependencies": {
		"@angular/compiler-cli": "4.0.0",
		"@angular/tsc-wrapped": "4.0.0",
		"@ionic/app-scripts": "1.3.0",
		"@types/node": "^7.0.12",
		"chalk": "^1.1.3",
		"codelyzer": "3.0.0-beta.4",
		"conventional-changelog": "^1.1.3",
		"cordova": "^6.5.0",
		"fs-extra": "^2.1.2",
		"googleapis": "^18.0.0",
		"ionic": "^2.2.2",
		"ionic-app-lib": "^2.2.1",
		"ip": "^1.1.5",
		"nodegit": "^0.18.0",
		"rollup-plugin-replace": "^1.1.1",
		"semver": "^5.3.0",
		"tslint": "^4.5.1",
		"typescript": "^2.2.2",
		"uuid": "^3.0.1",
		"xml2js": "^0.4.17",
		"yargs": "^7.0.2"
	},
	"engines": {
		"node": ">= 7.4"
	}
}
```

When I run `npm run ionic:lint --bailOnLintError` it seems to work just fine (or that's the impression it gives):
```text
➜  maintenance git:(master) npm run ionic:lint --bailOnLintError

> @infarm/maintenance@3.0.0 ionic:lint /Users/rolandjitsu/Projects/infarm/maintenance
> ionic-app-scripts lint

[21:48:55]  ionic-app-scripts 1.3.0 
[21:48:55]  lint started ... 
[21:48:57]  lint finished in 2.37 s 
```

But after I added a `console.log` in `utils/error.js` I now see:
```text
➜  maintenance git:(master) npm run ionic:lint --bailOnLintError

> @infarm/maintenance@3.0.0 ionic:lint /Users/rolandjitsu/Projects/infarm/maintenance
> ionic-app-scripts lint

[21:50:17]  ionic-app-scripts 1.3.0 
[21:50:17]  lint started ... 

            Could not find implementations for the following rules specified in the configuration:
            no-empty-interface
no-magic-numbers
prefer-for-of
array-type
arrow-return-shorthand
callable-types
import-spacing
interface-over-type-literal
match-default-export-name
no-unnecessary-initializer
prefer-function-over-method
prefer-method-signature
space-before-function-paren
max-classes-per-file
prefer-const
import-blacklist
no-duplicate-super
no-misused-new
no-string-throw
typeof-compare
import-destructuring-spacing
            Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
            If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        
{ message: '\n            Could not find implementations for the following rules specified in the configuration:\n            no-empty-interface\nno-magic-numbers\nprefer-for-of\narray-type\narrow-return-shorthand\ncallable-types\nimport-spacing\ninterface-over-type-literal\nmatch-default-export-name\nno-unnecessary-initializer\nprefer-function-over-method\nprefer-method-signature\nspace-before-function-paren\nmax-classes-per-file\nprefer-const\nimport-blacklist\nno-duplicate-super\nno-misused-new\nno-string-throw\ntypeof-compare\nimport-destructuring-spacing\n            Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.\n            If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.\n        ',
  name: 'Error',
  stack: 'Error: \n            Could not find implementations for the following rules specified in the configuration:\n            no-empty-interface\nno-magic-numbers\nprefer-for-of\narray-type\narrow-return-shorthand\ncallable-types\nimport-spacing\ninterface-over-type-literal\nmatch-default-export-name\nno-unnecessary-initializer\nprefer-function-over-method\nprefer-method-signature\nspace-before-function-paren\nmax-classes-per-file\nprefer-const\nimport-blacklist\nno-duplicate-super\nno-misused-new\nno-string-throw\ntypeof-compare\nimport-destructuring-spacing\n            Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.\n            If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.\n        \n    at new BuildError (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/@ionic/app-scripts/dist/util/errors.js:17:28)\n    at taskReject (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)\n    at /Users/rolandjitsu/Projects/infarm/maintenance/node_modules/@ionic/app-scripts/dist/worker-process.js:14:13',
  hasBeenLogged: false,
  isFatal: false }
[21:50:20]  lint finished in 3.46 s 
```

Which means it's not using the version I want (`v4.5`). It also seems to swallow the exception, never log it and never fails even if I provide the flag `--bailOnLintError`, which, according to the docs, should make the lint task fail if there were errors.

#### What behavior are you expecting?

Should use the tslint version I add in my `package.json` and should fail on error.

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

I'm using `v1.3.0`.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by danbucholtz** [comment]
app-scripts depends on tslint so it is going to use it's own version. I looked into upgrading to 4 a while back but it's non-trivial. Wanna do a PR? It may be easier now that we are on latest TypeScript.

Thanks,
Dan

**Comment by rolandjitsu** [comment]
@danbucholtz I figured. Sure, I'll give it a shot if nobody is working on it.

**Comment by danbucholtz** [comment]
@rolandjitsu,

I don't think anyone is. Are you in our slack? I'm happy to help guide you through it if you need some help.

Thanks,
Dan

**Comment by rolandjitsu** [comment]
@danbucholtz Ok. I'm not, but I will register.

I'll take a look at the impl. of the current TS linting process and I'll see if I understand how it works, otherwise I'll definitely write you and ask about what I don't understand.

**Comment by jgw96** [comment]
Closing this as the above PR got merged. Thanks, @rolandjitsu !
