### ISSUE TITLE
Autoreloader make crashing

### ISSUE THREAD

**Issue by ScreamZ** [driftyco/ionic-app-scripts#902]
#### Short description of the problem:
Auto-reloading sometimes crash unexpectedly.

**Steps to reproduce:**
1. ionic serve
2. visit localhost:8100
3. modify code, and sometimes it crashes with message

```

/home/screamz/js-dev/picoloGame/node_modules/ws/lib/Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (/home/screamz/js-dev/picoloGame/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish (/home/screamz/js-dev/picoloGame/node_modules/ws/lib/Receiver.js:673:19)
    at Receiver.expectHandler (/home/screamz/js-dev/picoloGame/node_modules/ws/lib/Receiver.js:661:33)
    at Receiver.add (/home/screamz/js-dev/picoloGame/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/home/screamz/js-dev/picoloGame/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Which @ionic/app-scripts version are you using?**
1.3.2

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Seems started after using https://github.com/deepstreamIO/deepstream.io-client-js that is also opening a websocket

**Comment by ScreamZ** [comment]
Seems related to a bug in ws library, can we consider an upgrade to 2.1 ?

**Comment by tzsk** [comment]
Well, I did run `npm install ws` and it updated the `ws` version to `"version": "2.2.3"`. But it still isn't working.
Now it won't even load the first time. 

Previously it was loading the first time and breaking the 2nd time. Now it is crashing in the first attempt.

**Comment by ScreamZ** [comment]
Try to add ws to your home project too and try again ?

**Comment by dimorphic** [comment]
Same problem here, using @ionic/app-scripts 1.3.0:

```js
<PROJECT_ROOT>/node_modules/@ionic/app-scripts/node_modules/ws/lib/Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (<PROJECT_ROOT>/node_modules/@ionic/app-scripts/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish (<PROJECT_ROOT>/node_modules/@ionic/app-scripts/node_modules/ws/lib/Receiver.js:673:19)
    at Receiver.expectHandler (<PROJECT_ROOT>/node_modules/@ionic/app-scripts/node_modules/ws/lib/Receiver.js:661:33)
    at Receiver.add (<PROJECT_ROOT>/node_modules/@ionic/app-scripts/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (<PROJECT_ROOT>/node_modules/@ionic/app-scripts/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
`

@ScreamZ: any temp fix for this ?

**Comment by ScreamZ** [comment]
I've upgraded all my libs to the highest version au ws and i used ws in my dependencies. it fixed

**Comment by tzsk** [comment]
I've fixed it. I tried uninstalling ionic and installing it again. 

```bash
npm uninstall -g ionic
```

then 

```bash
npm install -g ionic
```

Then created a new project and copied the `src` directory content over there. Now it's perfect. No issue what so ever.

I've noticed this issue occurs when we update global ionic. I think it creates 2 separate folders for different versions of ionic rather than overwriting the old one. And it creates ambiguity while creating project dependencies.

**Comment by Chinafreak** [comment]
I've same problem and I would love to have a temp fix for that. Before it was working all fine. But then everytime when I quit the tab/close windows (and/or sometimes at runtime), then I got this error:

`
TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (C:\Users\Yan-MacBook\Documents\challenge-games\Challenge-Games\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:306:46)
    at Receiver.finish (C:\Users\Yan-MacBook\Documents\challenge-games\Challenge-Games\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:673:19)
    at Receiver.expectHandler (C:\Users\Yan-MacBook\Documents\challenge-games\Challenge-Games\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:661:33)
    at Receiver.add (C:\Users\Yan-MacBook\Documents\challenge-games\Challenge-Games\node_modules\@ionic\app-scripts\node_modules\ws\lib\Receiver.js:103:24)
    at Socket.realHandler (C:\Users\Yan-MacBook\Documents\challenge-games\Challenge-Games\node_modules\@ionic\app-scripts\node_modules\ws\lib\WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
`

**Comment by Chinafreak** [comment]
**I found way to fix it:**

node_modules/@ionic/app-scripts/node_modules/ws/lib/Receiver.js

change from line 11

", bufferUtil = require('./BufferUtil').BufferUtil"

to 

", bufferUtil = require('./BufferUtil')"

then its works everything fine.
I could commit this, but there is no node_modules here at git.

**Comment by joshterrill** [comment]
@Chinafreak this fix would not go into the ionic project anyway. It is part of the websocket library, so you would need to commit the change there - which if you actually go to the `ws` github repo, you'll see that this change has already been made and checked into it under version `3.0.0`

https://github.com/websockets/ws/blob/master/lib/Receiver.js#L13

**Comment by alllx** [comment]
@Ionic team please update ws dependency to 1.1.4.
I updated ws to 1.1.4 inside app-scripts and it solved reloading problem.
cd ./node_modules/@ionic/app-scripts
npm install ws@1.1.4 -S

**Comment by joshterrill** [comment]
Thank @alllx, it would be great if we could merge this into the project!
