### ISSUE TITLE
Uglifyjs prod fails after upgrading to ionic v3

### ISSUE THREAD

**Issue by aemr3** [driftyco/ionic-app-scripts#915]
Hi, I am using the latest version of ionic. After upgrading to v3, I got this error:

```
[01:02:51]  ionic-app-scripts 1.3.4
[01:02:51]  build prod started ...
[01:02:51]  clean started ...
[01:02:51]  clean finished in 3 ms
[01:02:51]  copy started ...
[01:02:51]  ngc started ...
[01:03:14]  ngc finished in 22.92 s
[01:03:14]  preprocess started ...
[01:03:14]  deeplinks started ...
[01:03:18]  deeplinks finished in 3.57 s
[01:03:18]  optimization started ...
[01:03:18]  copy finished in 27.09 s
[01:03:53]  optimization finished in 35.26 s
[01:03:53]  preprocess finished in 38.84 s
[01:03:53]  webpack started ...
[01:05:49]  webpack finished in 116.19 s
[01:05:49]  sass started ...
[01:05:49]  uglifyjs started ...
[01:05:51]  sass finished in 1.78 s
[01:05:51]  cleancss started ...
[01:05:53]  cleancss finished in 2.20 s
[01:06:01]  ionic-app-script task: "build"
[01:06:01]  Error: Cannot set property 'fixed' of undefined in undefined at line undefined, col undefined, pos undefined
Error: Cannot set property 'fixed' of undefined in undefined at line undefined, col undefined, pos undefined
    at new BuildError (.../node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (.../node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at .../node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

System information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by danbucholtz** [comment]
How can I recreate this issue? Please provide a minimal Github repository.

Thanks,
Dan

**Comment by aemr3** [comment]
Found the problem after digging into source code of uglify-js. It was related with uglify-js itself. Somehow it wasn't resolving undefined variables. Thanks anyway.

**Comment by wleberre** [comment]
Can you explain how you resolve it ? 
Thanks

**Comment by danbucholtz** [comment]
I think this is a one-off issue that was likely resolved by updating uglify.

Thanks,
Dan
