### ISSUE TITLE
`gulp e2e.watch` error on windows

### ISSUE THREAD

**Issue by AmitMY** [driftyco/ionic-app-scripts#924]
#### Short description of the problem:
Running `gulp e2e.watch --folder split-pane` (or any folder) results in an error on Windows
Error:
![image](https://cloud.githubusercontent.com/assets/5757359/25447739/0306006a-2abf-11e7-877b-8751070616d1.png)

#### What behavior are you expecting?
For it to work :)

**Steps to reproduce:**
1. Pull ionic (on windows)
2. `npm install`
3. `gulp e2e.watch --folder split-pane`

This is the `/node_modules/.bin/ionic-app-scripts` file
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac
if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../@ionic/app-scripts/bin/ionic-app-scripts.js" "$@"
  ret=$?
else 
  node  "$basedir/../@ionic/app-scripts/bin/ionic-app-scripts.js" "$@"
  ret=$?
fi
exit $ret
```

**Which @ionic/app-scripts version are you using?** 1.3.4

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

> D:\xampp\htdocs\Forks\ionic>gulp e2e.watch --folder split-pane
> [20:31:07] Using gulpfile D:\xampp\htdocs\Forks\ionic\gulpfile.js
> [20:31:07] Starting 'e2e.prepare'...
> [20:31:07] Starting 'e2e.clean'...
> [20:31:07] Finished 'e2e.clean' after 42 ms
> [20:31:07] Starting 'e2e.polyfill'...
> [20:31:14] Finished 'e2e.polyfill' after 6.44 s
> [20:31:14] Starting 'e2e.prepareSass'...
> [20:31:14] Finished 'e2e.prepareSass' after 3.15 ms
> [20:31:14] Finished 'e2e.prepare' after 6.49 s
> [20:31:14] Starting 'e2e.watch'...
> Running ionic-app-scripts serve with split-pane/basic
> node ./node_modules/.bin/ionic-app-scripts serve --appEntryPoint D:\xampp\htdocs\Forks\ionic\src\components\split-pane\test\basic\app\main.ts --appNgModulePath D:\xampp\htdocs\Forks\i
> onic\src\components\split-pane\test\basic\app\app.module.ts --deepLinksDir D:\xampp\htdocs\Forks\ionic\src\components\split-pane\test\basic --srcDir D:\xampp\htdocs\Forks\ionic\src --
> wwwDir D:\xampp\htdocs\Forks\ionic\dist\e2e\components\split-pane\test\basic\www --tsconfig D:\xampp\htdocs\Forks\ionic\dist\e2e\components\split-pane\test\basic\tsconfig.json --readC
> onfigJson false --ionicAngularDir D:\xampp\htdocs\Forks\ionic\src --sass scripts\e2e\sass.config.js --copy scripts\e2e\copy.config.js --enableLint false
> D:\xampp\htdocs\Forks\ionic\node_modules\.bin\ionic-app-scripts:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> SyntaxError: missing ) after argument list
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> [20:31:14] 'e2e.watch' errored after 119 ms
> [20:31:14] Error: App-scripts failed with non-zero status code
>     at ChildProcess.<anonymous> (D:\xampp\htdocs\Forks\ionic\scripts\gulp\util.ts:228:14)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by 5im0n** [comment]
I have the same error on Windows

**Comment by akaztp** [comment]
The problem also exists on the Linux Subsystem for Windows.

**Comment by AmitMY** [comment]
@akaztp If you mean "Bash on Windows", it does work there, but you need the unix type of packages. remove your node_modules directory, and from "Bash on Windows" in your mounted directory run `npm install`
