### ISSUE TITLE
Ionic app-scripts build fails, source-map

### ISSUE THREAD

**Issue by tordnilsen** [driftyco/ionic-app-scripts#935]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Build fails.

#### What behavior are you expecting?
It should work as expected. Had no problems yesterday.

**Steps to reproduce:**
1. Use Ionic 2.2.3
2. Ionic --serve

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
@ionic/app-scripts@1.3.6

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

C:\project\node_modules\source-map\lib\source-node.js:115
        node.add(nextLine.substr(0, mapping.generatedColumn));
                         ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (C:\project\node_modules\source-map\lib\source-node.js:115:26)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\project\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\project\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (C:\project\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (C:\project\node_modules\webpack-sources\lib\ReplaceSource.js:69:29)
    at CachedSource.node (C:\project\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at C:\Users\Tord\dev\industribyen\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\project\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
npm ERR! code ELIFECYCLE

**Comment by danbucholtz** [comment]
Hmmm, that seems strange. How can I recreate?

Thanks,
Dan

**Comment by speedfl** [comment]
I had this issue! 

Simple solution => only one component per file and it is solve

Keep me posted!

**Comment by jgw96** [comment]
@tordnilsen did you have two components in one file when getting this error?
