### ISSUE TITLE
error from 1.3.4 to 1.3.6

### ISSUE THREAD

**Issue by yozman** [driftyco/ionic-app-scripts#941]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
```
Runtime Error
Uncaught (in promise): Error: Cannot find module '../pages/login/login.module'.
Error: Cannot find module '../pages/login/login.module'.
    at new Error (native)
    at Error.d (http://localhost:8100/build/polyfills.js:3:3991)
    at webpackEmptyContext (http://localhost:8100/build/main.js:76101:8)
    at loadAndCompile (http://localhost:8100/build/main.js:75124:36)
    at NgModuleLoader.load (http://localhost:8100/build/main.js:75089:83)
    at ModuleLoader.load (http://localhost:8100/build/main.js:54859:44)
    at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:26284:39)
    at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:26267:25)
    at getComponent (http://localhost:8100/build/main.js:29342:23)
    at convertToView (http://localhost:8100/build/main.js:29360:16)
    at convertToViews (http://localhost:8100/build/main.js:29379:32)
    at NavControllerBase._loadLazyLoading (http://localhost:8100/build/main.js:43079:108)
    at http://localhost:8100/build/main.js:43015:46
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11562)
    at Object.inner.inner.fork.onInvoke (http://localhost:8100/build/main.js:4403:37)

Stack
Error: Uncaught (in promise): Error: Cannot find module '../pages/login/login.module'.
Error: Cannot find module '../pages/login/login.module'.
    at new Error (native)
    at Error.d (http://localhost:8100/build/polyfills.js:3:3991)
    at webpackEmptyContext (http://localhost:8100/build/main.js:76101:8)
    at loadAndCompile (http://localhost:8100/build/main.js:75124:36)
    at NgModuleLoader.load (http://localhost:8100/build/main.js:75089:83)
    at ModuleLoader.load (http://localhost:8100/build/main.js:54859:44)
    at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:26284:39)
    at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:26267:25)
    at getComponent (http://localhost:8100/build/main.js:29342:23)
    at convertToView (http://localhost:8100/build/main.js:29360:16)
    at convertToViews (http://localhost:8100/build/main.js:29379:32)
    at NavControllerBase._loadLazyLoading (http://localhost:8100/build/main.js:43079:108)
    at http://localhost:8100/build/main.js:43015:46
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11562)
    at Object.inner.inner.fork.onInvoke (http://localhost:8100/build/main.js:4403:37)
    at new Error (native)
    at Error.d (http://localhost:8100/build/polyfills.js:3:3991)
    at l (http://localhost:8100/build/polyfills.js:3:3244)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:2600)
    at NavControllerBase._fireError (http://localhost:8100/build/main.js:42989:16)
    at NavControllerBase._failed (http://localhost:8100/build/main.js:42977:14)
    at http://localhost:8100/build/main.js:43032:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11562)
    at Object.inner.inner.fork.onInvoke (http://localhost:8100/build/main.js:4403:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11502)
    at n.run (http://localhost:8100/build/polyfills.js:3:6468)
    at http://localhost:8100/build/polyfills.js:3:3767
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12256)
    at Object.inner.inner.fork.onInvokeTask (http://localhost:8100/build/main.js:4394:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12177)
```

#### What behavior are you expecting?

**Steps to reproduce:**
1. clone https://github.com/langcrew/ion-17-peach-mall
2. install node_modules
3. npm run dev

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
from 1.3.4 to 1.3.6 (error is 1.3.6)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by yozman** [comment]
@danbucholtz 
the last version works is 1.3.3
wish u fix it as soon as posible

**Comment by danbucholtz** [comment]
I'll check it out.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I cannot recreate this issue. I am able to run `ionic serve` and `npm run ionic:build --prod` and cruise around the app without issue.

Can you try the two commands and see if they work? I'll re-open if needed.

Thanks,
Dan

**Comment by yozman** [comment]
@danbucholtz 
yeah, still error,
the error is not in terminal,
when I open browser
the page goes on the error message

**Comment by danbucholtz** [comment]
How can I recreate it? I cloned your app, and everything went fine.

Thanks,
Dan

**Comment by yozman** [comment]
@danbucholtz 
maybe you can do this,
1. clone repo: <https://github.com/langcrew/ion-17-songguo>
2. install cnpm: `npm install -g cnpm --registry=https://registry.npm.taobao.org`
3. install node_modules: `cnpm i`
4. serve it: `npm run dev`
5. open browser: <localhost:8100>
6. u will see the error

**Comment by danbucholtz** [comment]
What is `cnpm`?

**Comment by yozman** [comment]
@danbucholtz 
most Chinese use cnpm instead of npm
u can check it at <https://npm.taobao.org/>

it's made by alibaba
