### ISSUE TITLE
Cannot run sidemenu starter app from fresh install of ionic.

### ISSUE THREAD

**Issue by rmgpinto** [driftyco/ionic-app-scripts#951]
#### Short description of the problem:
Cannot run sidemenu starter app from fresh install of ionic.

#### What behavior are you expecting?
Build the starer app.

**Steps to reproduce:**
1. npm install -g cordova ionic
2. ionic start webapp sidemenu
3. ionic serve

```
$ ionic serve
...
[08:06:46]  ionic-app-scripts 1.3.6 
[08:06:46]  watch started ... 
[08:06:46]  build dev started ... 
[08:06:46]  clean started ... 
[08:06:46]  clean finished in 1 ms 
[08:06:46]  copy started ... 
[08:06:46]  transpile started ... 
[08:06:54]  transpile finished in 7.87 s 
[08:06:54]  preprocess started ... 
[08:06:54]  deeplinks started ... 
[08:06:54]  ionic-app-script task: "serve" 
[08:06:54]  Error: Cannot read property 'content' of undefined 
Error: Cannot read property 'content' of undefined
    at BuildError.Error (native)
    at new BuildError (/webapp/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /webapp/node_modules/@ionic/app-scripts/dist/preprocess.js:18:21
...
```

**Which @ionic/app-scripts version are you using?**
1.3.6

**Comment by danbucholtz** [comment]
Hi @rmgpinto,

I am unable to recreate this. It is running just fine for me.

Can you try this? Our new CLI is in the final stages of testing so maybe something went wrong there.

```
npm uninstall -g ionic (may require sudo)
npm install -g ionic@beta
```
and then try the project again?

I'll re-open if this is still an issue.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Did you modify your app to change the location of `app.module.ts` by any chance?

Thanks,
Dan

**Comment by rmgpinto** [comment]
Now I get a Segmentation Fault:
`Starting app-scripts server: --port 8100 --livereload-port 35729 --address 0.0.0.0

[16:29:21]  watch started ... 
[16:29:21]  build dev started ... 
[16:29:21]  clean started ... 
[16:29:21]  clean finished in 2 ms 
[16:29:21]  copy started ... 
[16:29:21]  transpile started ... 
[16:29:23]  transpile finished in 2.71 s 
[16:29:23]  preprocess started ... 
[16:29:23]  deeplinks started ... 
[16:29:23]  deeplinks finished in 20 ms 
[16:29:23]  preprocess finished in 22 ms 
[16:29:23]  webpack started ... 
[16:29:24]  copy finished in 3.01 s 
[16:29:32]  webpack finished in 8.46 s 
[16:29:32]  sass started ... 
Segmentation fault
`
I've pinpointed this to sass, if I remove sass.config.js on app-scripts dir, ionic serve will go through, but then I have no css.

**Comment by danbucholtz** [comment]
What version of node do you have? What are you doing that is unique that requires a custom sass config?

Thanks,
Dan

**Comment by rmgpinto** [comment]
@danbucholtz 
Node 7.2.1

I'm doing nothing really, this is a fresh install on an Alpine Linux.

**Comment by danbucholtz** [comment]
It could have something to do with linux, I'm not sure.

Thanks,
Dan
