### ISSUE TITLE
Undefined 'items' error when implementing a modal with templateUrl

### ISSUE THREAD

**Issue by royalcheeseburger** [driftyco/ionic-app-scripts#995]
#### Short description of the problem:
Receive an undefined error when presenting a modal that has its own .ts file and .html file as templateUrl

#### What behavior are you expecting?
I expect the modal to present without any error.

**Steps to reproduce:**
1.Call presentNewLocationModal()
2.Error is thrown
3.Note that the constructor is well called

```
// new-location-modal.ts
import { Component } from '@angular/core';
import { Platform, NavParams, ViewController } from 'ionic-angular';

@Component({
  templateUrl: "new-location-modal.html"
})
export class NewLocationModalPage {

  constructor(public platform: Platform, public viewCtrl: ViewController) {
    console.log('NewLocationModal#constructor');
  }

  dismiss() {
    this.viewCtrl.dismiss();
  }
}
```

```
// new-location-modal.html
<ion-header>
  <ion-toolbar>
    <ion-title>
     Title
    </ion-title>
    </ion-toolbar>
</ion-header>
<ion-content>
  Content
</ion-content>
```

```
// new-event.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ModalController, NavController, NavParams } from 'ionic-angular';
import { Platform, ViewController } from 'ionic-angular';

import { NewLocationModalPage } from '../../modals/new-location/new-location-modal';

@Component({
  selector: 'page-new-event',
  templateUrl: 'new-event.html'
})
export class NewEventPage {
  newEventForm: FormGroup;

  timeStarts: string = '';

  constructor(public modalCtrl: ModalController, public formBuilder: FormBuilder) {
    // Creating the newEventForm and specifying controls
    this.newEventForm = this.formBuilder.group({
      title: ['', Validators.required],
      sport: ['', Validators.required],
      timeStarts: ['', Validators.required],
      location: ['', Validators.required]
    });
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad NewEventPage');
  }

  presentNewLocationModal() {
    let modal = this.modalCtrl.create(NewLocationModalPage);
    modal.present();
  }
}
```

**Which @ionic/app-scripts version are you using?**
"1.1.4"

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Error:
```
EXCEPTION: Error in ./NewLocationModal class NewLocationModal - inline template:22:14 caused by: Cannot read property 'items' of undefined

TypeError: Cannot read property 'items' of undefined
    at CompiledTemplate.proxyViewClass.View_NewLocationModal0.detectChangesInternal (/AppModule/NewLocationModal/component.ngfactory.js:363:46)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:8100/build/main.js:117516:18)
    at CompiledTemplate.proxyViewClass.View_NewLocationModal_Host0.detectChangesInternal (/AppModule/NewLocationModal/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
    at ViewContainer.detectChangesInNestedViews (http://localhost:8100/build/main.js:117863:37)
    at CompiledTemplate.proxyViewClass.View_ModalCmp0.detectChangesInternal (/IonicModule/ModalCmp/component.ngfactory.js:46:14)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:8100/build/main.js:117516:18)
    at CompiledTemplate.proxyViewClass.View_ModalCmp_Host0.detectChangesInternal (/IonicModule/ModalCmp/host.ngfactory.js:30:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:8100/build/main.js:117531:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:8100/build/main.js:117726:44)
```
StackOverflow:  http://stackoverflow.com/questions/44019627/ionic-2-modal-inline-template-typeerror-cannot-read-property-items-of-unde
Ionic Forum: https://forum.ionicframework.com/t/modalcmp-ionviewpreload-error/73988

**Comment by royalcheeseburger** [comment]
Wrong section
