### ISSUE TITLE
build in prod mode error because ionic-angular use default parameters value

### ISSUE THREAD

**Issue by patou** [driftyco/ionic-app-scripts#999]
#### Short description of the problem:
When I build the project with the prod mode I have an error : 
```
> ionic-app-scripts build "--prod"

[11:20:25]  ionic-app-scripts 1.3.4
[11:20:25]  build prod started ...
[11:20:25]  clean started ...
[11:20:25]  clean finished in 38 ms
[11:20:25]  copy started ...
[11:20:25]  ngc started ...
[11:20:41]  ngc finished in 15.82 s
[11:20:41]  preprocess started ...
[11:20:41]  deeplinks started ...
[11:20:42]  deeplinks finished in 756 ms
[11:20:42]  optimization started ...
[11:20:43]  copy finished in 17.44 s
[11:21:02]  optimization finished in 20.61 s
[11:21:02]  preprocess finished in 21.37 s
[11:21:02]  webpack started ...
[11:23:05]  webpack finished in 122.52 s
[11:23:05]  sass started ...
[11:23:05]  uglifyjs started ...
[11:23:08]  ionic-app-script task: "build"
[11:23:08]  Error: Unexpected token operator «=», expected punc «,» in
            c:\Users\p.desaintsteban\projets\biocfrais\frontend\www\build\0.main.js at line 16405, col 38, pos 595031
Error: Unexpected token operator «=», expected punc «,» in c:\Users\p.desaintsteban\projets\biocfrais\frontend\www\build\0.main.js at line 16405, col 38, pos 595031
    at BuildError.Error (native)
    at new BuildError (c:\Users\p.desaintsteban\projets\biocfrais\frontend\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at taskReject (c:\Users\p.desaintsteban\projets\biocfrais\frontend\node_modules\@ionic\app-scripts\dist\worker-process.js:36:22)
    at c:\Users\p.desaintsteban\projets\biocfrais\frontend\node_modules\@ionic\app-scripts\dist\worker-process.js:14:13
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

The error ligne in the 0.main.js is : 
```
/**
 * @hidden
 * @param {?} fn
 * @param {?} wait
 * @param {?=} immediate
 * @return {?}
 */
function debounce(fn, wait, immediate = false) {
[...]
}
```

This code come frome the ionic-angular/es2015/util.js file

@ionic/app-scripts : 1.3.4
ionic-angular: 3.1.0

**Comment by patou** [comment]
I try update to app-script : 1.3.7 and ionic-angular: 3.2.0
And the same error.

**Comment by rapropos** [comment]
#954 looks potentially related.

**Comment by fsalomon** [comment]
I had a similar issue. For me it helped removing an `import {removeArrayItem} from "ionic-angular/es2015/util/util";` and replacing `removeArrayItem` with lodash's `_.pull()`.
